import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";
import StaffTicketDetail from "../../src/StaffTicketDetail.js";
import * as api from "../../src/api.js";

vi.mock("../../src/api.js", async () => ({ ...(await vi.importActual<typeof import("../../src/api.js")>("../../src/api.js")), fetchStaffTicketDetail: vi.fn(), fetchAssignableStaff: vi.fn(), assignStaffTicket: vi.fn(), updateStaffPriority: vi.fn(), updateStaffStatus: vi.fn(), createStaffComment: vi.fn(), createStaffNote: vi.fn() }));
const actor = { id: 2, name: "Mali Support", email: "mali.staff@example.test", role: "IT_STAFF" as const, isActive: true, mustChangePassword: false }; const ticket = { id: 42, ticketNumber: "TKT-20260908-10000000", requester: { id: 1, name: "Jennifer", email: "j@example.test" }, category: { id: 1, name: "Hardware" }, relatedSystem: { id: 1, name: "Laptop" }, summary: "VPN unavailable", requestedPriority: "HIGH" as const, itPriority: "HIGH" as const, currentStatus: "OPEN" as const, owner: null, requesterResolvedAt: null, createdAt: "2026-09-08T00:00:00Z", updatedAt: "2026-09-08T00:00:00Z", ticketDate: "2026-09-08T00:00:00Z", description: "VPN unavailable", attachments: [], publicComments: [], internalNotes: [] };
describe("Lab 3 IT Staff ticket detail", () => { it("supports claim and private note controls", async () => { vi.mocked(api.fetchStaffTicketDetail).mockResolvedValue(ticket); vi.mocked(api.fetchAssignableStaff).mockResolvedValue([actor]); vi.mocked(api.assignStaffTicket).mockResolvedValue({ ...ticket, owner: actor }); const user = userEvent.setup(); render(<StaffTicketDetail ticketId={42} currentUser={actor} onBack={vi.fn()} />); expect(await screen.findByRole("heading", { name: ticket.ticketNumber })).toBeInTheDocument(); await user.click(screen.getByRole("button", { name: "Claim for me" })); expect(api.assignStaffTicket).toHaveBeenCalledWith(42, 2); expect(screen.getByText(/private to it staff/i)).toBeInTheDocument(); }); });
