import request from "supertest";
import { UserRole } from "@prisma/client";
import { beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({ sessionFindUnique: vi.fn(), ticketFindFirst: vi.fn(), ticketFindUnique: vi.fn(), actionFindMany: vi.fn(), actionFindFirst: vi.fn(), actionCreate: vi.fn(), actionUpdate: vi.fn(), actionUpdateMany: vi.fn(), actionFindUniqueOrThrow: vi.fn() }));
vi.mock("../../src/prisma.js", () => ({ getPrisma: () => ({ session: { findUnique: mocks.sessionFindUnique }, ticket: { findFirst: mocks.ticketFindFirst, findUnique: mocks.ticketFindUnique }, actionTaken: { findMany: mocks.actionFindMany, findFirst: mocks.actionFindFirst, create: mocks.actionCreate, update: mocks.actionUpdate, updateMany: mocks.actionUpdateMany, findUniqueOrThrow: mocks.actionFindUniqueOrThrow } }) }));
import { app } from "../../src/app.js";

const action = { id: 9, ticketId: 42, actionDateTime: new Date("2026-09-22T09:30:00.000Z"), description: "Checked logs.", result: "Failure reproduced.", performedById: 2, followUpRequired: false, followUpNote: null, attachmentNotes: null, createdAt: new Date("2026-09-22T09:31:00.000Z"), updatedAt: new Date("2026-09-22T09:31:00.000Z"), performedBy: { id: 2, name: "Mali Staff", email: "mali@example.test", role: UserRole.IT_STAFF } };
function signIn(role: UserRole, id = role === UserRole.REQUESTER ? 1 : 2) { mocks.sessionFindUnique.mockResolvedValue({ expiresAt: new Date(Date.now() + 60_000), user: { id, name: role, email: `${role.toLowerCase()}@example.test`, role, isActive: true, mustChangePassword: false } }); return "toktickit_session=lab4-token"; }

describe("Lab 4 Actions Taken API", () => {
  beforeEach(() => vi.clearAllMocks());
  it("requires authentication", async () => { const response = await request(app).get("/api/tickets/42/actions"); expect(response.status).toBe(401); });
  it("lists Actions Taken only for an owned Requester Ticket", async () => { const cookie = signIn(UserRole.REQUESTER, 1); mocks.ticketFindFirst.mockResolvedValueOnce({ id: 42 }).mockResolvedValueOnce(null); mocks.actionFindMany.mockResolvedValue([action]); const own = await request(app).get("/api/tickets/42/actions").set("Cookie", cookie); const foreign = await request(app).get("/api/tickets/43/actions").set("Cookie", cookie); expect(own.status).toBe(200); expect(own.body.data.items[0]).toMatchObject({ id: 9, performedBy: { id: 2 } }); expect(foreign.status).toBe(404); });
  it("derives the performer from the authenticated Staff session", async () => { const cookie = signIn(UserRole.IT_STAFF, 2); mocks.ticketFindUnique.mockResolvedValue({ id: 42 }); mocks.actionCreate.mockResolvedValue(action); const response = await request(app).post("/api/staff/tickets/42/actions").set("Cookie", cookie).send({ actionDateTime: "2026-09-22T09:30:00.000Z", description: "Checked logs.", result: "Failure reproduced.", followUpRequired: false }); expect(response.status).toBe(201); expect(mocks.actionCreate).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ performedById: 2, followUpNote: null }) })); });
  it("requires a Follow-Up Note when follow-up is required", async () => { const cookie = signIn(UserRole.IT_STAFF); const response = await request(app).post("/api/staff/tickets/42/actions").set("Cookie", cookie).send({ actionDateTime: "2026-09-22T09:30:00.000Z", description: "Checked logs.", result: "Failure reproduced.", followUpRequired: true }); expect(response.status).toBe(400); expect(response.body.error.code).toBe("VALIDATION_ERROR"); expect(mocks.actionCreate).not.toHaveBeenCalled(); });
  it("rejects a stale Action Taken update without overwriting it", async () => { const cookie = signIn(UserRole.ADMINISTRATOR, 3); mocks.actionFindFirst.mockResolvedValue({ id: 9, updatedAt: new Date("2026-09-22T09:31:00.000Z") }); mocks.actionUpdateMany.mockResolvedValue({ count: 0 }); const response = await request(app).patch("/api/staff/tickets/42/actions/9").set("Cookie", cookie).send({ actionDateTime: "2026-09-22T09:30:00.000Z", description: "Changed.", result: "Changed.", followUpRequired: false, updatedAt: "2026-09-22T09:30:00.000Z" }); expect(response.status).toBe(409); expect(response.body.error.code).toBe("ACTION_UPDATE_CONFLICT"); expect(mocks.actionUpdate).not.toHaveBeenCalled(); });
  it("does not let a Requester create a Staff Action Taken", async () => { const cookie = signIn(UserRole.REQUESTER, 1); const response = await request(app).post("/api/staff/tickets/42/actions").set("Cookie", cookie).send({}); expect(response.status).toBe(403); expect(response.body.error.code).toBe("ROLE_FORBIDDEN"); });
});
