import { createHash } from "node:crypto";
import request from "supertest";
import { Prisma, UserRole } from "@prisma/client";
import { beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({ sessionFindUnique: vi.fn(), ticketFindFirst: vi.fn(), ticketFindUnique: vi.fn(), actionFindMany: vi.fn(), actionFindFirst: vi.fn(), actionFindUnique: vi.fn(), actionCreate: vi.fn(), actionUpdateMany: vi.fn(), actionFindUniqueOrThrow: vi.fn() }));
vi.mock("../../src/prisma.js", () => ({ getPrisma: () => ({ session: { findUnique: mocks.sessionFindUnique }, ticket: { findFirst: mocks.ticketFindFirst, findUnique: mocks.ticketFindUnique }, actionTaken: { findMany: mocks.actionFindMany, findFirst: mocks.actionFindFirst, findUnique: mocks.actionFindUnique, create: mocks.actionCreate, updateMany: mocks.actionUpdateMany, findUniqueOrThrow: mocks.actionFindUniqueOrThrow } }) }));
import { app } from "../../src/app.js";

const action = { id: 9, ticketId: 42, actionDateTime: new Date("2026-09-22T09:30:00.000Z"), description: "Checked logs.", result: "Failure reproduced.", performedById: 2, followUpRequired: false, followUpNote: null, attachmentNotes: null, createdAt: new Date("2026-09-22T09:31:00.000Z"), updatedAt: new Date("2026-09-22T09:31:00.000Z"), performedBy: { id: 2, name: "Mali Staff", email: "mali@example.test", role: UserRole.IT_STAFF } };
function signIn(role: UserRole, id = role === UserRole.REQUESTER ? 1 : 2) { mocks.sessionFindUnique.mockResolvedValue({ expiresAt: new Date(Date.now() + 60_000), user: { id, name: role, email: `${role.toLowerCase()}@example.test`, role, isActive: true, mustChangePassword: false } }); return "toktickit_session=lab4-token"; }

describe("Lab 4 Actions Taken API", () => {
  beforeEach(() => vi.clearAllMocks());
  const idempotencyKey = "a4d4aead-1234-4abc-8abc-123456789abc";
  const requestFingerprint = createHash("sha256").update(JSON.stringify({ ticketId: 42, performerId: 2, actionDateTime: new Date("2026-09-22T09:30:00.000Z"), description: "Checked logs.", result: "Failure reproduced.", followUpRequired: false, followUpNote: null, attachmentNotes: null, expectedUpdatedAt: undefined })).digest("hex");
  it("requires authentication", async () => { const response = await request(app).get("/api/tickets/42/actions"); expect(response.status).toBe(401); });
  it("lists Actions Taken only for an owned Requester Ticket", async () => { const cookie = signIn(UserRole.REQUESTER, 1); mocks.ticketFindFirst.mockResolvedValueOnce({ id: 42 }).mockResolvedValueOnce(null); mocks.actionFindMany.mockResolvedValue([action]); const own = await request(app).get("/api/tickets/42/actions").set("Cookie", cookie); const foreign = await request(app).get("/api/tickets/43/actions").set("Cookie", cookie); expect(own.status).toBe(200); expect(own.body.data.items[0]).toMatchObject({ id: 9, performedBy: { id: 2 } }); expect(foreign.status).toBe(404); });
  it("returns only contract fields for performedBy", async () => { const cookie = signIn(UserRole.REQUESTER, 1); mocks.ticketFindFirst.mockResolvedValue({ id: 42 }); mocks.actionFindMany.mockResolvedValue([action]); const response = await request(app).get("/api/tickets/42/actions").set("Cookie", cookie); expect(response.status).toBe(200); expect(response.body.data.items[0].performedBy).toEqual({ id: 2, name: "Mali Staff" }); });
  it("allows IT Staff to list Actions Taken for an existing Ticket", async () => { const cookie = signIn(UserRole.IT_STAFF, 2); mocks.ticketFindFirst.mockResolvedValue({ id: 42 }); mocks.actionFindMany.mockResolvedValue([action]); const response = await request(app).get("/api/staff/tickets/42/actions").set("Cookie", cookie); expect(response.status).toBe(200); expect(response.body.data.items).toHaveLength(1); expect(mocks.actionFindMany).toHaveBeenCalledWith(expect.objectContaining({ where: { ticketId: 42 } })); });
  it("allows Administrator to list Actions Taken for an existing Ticket", async () => { const cookie = signIn(UserRole.ADMINISTRATOR, 3); mocks.ticketFindFirst.mockResolvedValue({ id: 42 }); mocks.actionFindMany.mockResolvedValue([action]); const response = await request(app).get("/api/staff/tickets/42/actions").set("Cookie", cookie); expect(response.status).toBe(200); expect(response.body.data.items).toHaveLength(1); });
  it("derives the performer from the authenticated Staff session", async () => { const cookie = signIn(UserRole.IT_STAFF, 2); mocks.ticketFindUnique.mockResolvedValue({ id: 42 }); mocks.actionFindUnique.mockResolvedValue(null); mocks.actionCreate.mockResolvedValue(action); const response = await request(app).post("/api/staff/tickets/42/actions").set("Cookie", cookie).set("Idempotency-Key", idempotencyKey).send({ actionDateTime: "2026-09-22T09:30:00.000Z", description: "Checked logs.", result: "Failure reproduced.", followUpRequired: false }); expect(response.status).toBe(201); expect(response.body.data.item).toMatchObject({ id: 9, ticketId: 42 }); expect(mocks.actionCreate).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ idempotencyKey, idempotencyFingerprint: expect.stringMatching(/^[0-9a-f]{64}$/), performedById: 2, followUpNote: null }) })); });
  it("allows Administrator to create an Action Taken", async () => { const cookie = signIn(UserRole.ADMINISTRATOR, 3); mocks.ticketFindUnique.mockResolvedValue({ id: 42 }); mocks.actionFindUnique.mockResolvedValue(null); mocks.actionCreate.mockResolvedValue(action); const response = await request(app).post("/api/staff/tickets/42/actions").set("Cookie", cookie).set("Idempotency-Key", idempotencyKey).send({ actionDateTime: "2026-09-22T09:30:00.000Z", description: "Checked logs.", result: "Failure reproduced.", followUpRequired: false }); expect(response.status).toBe(201); expect(mocks.actionCreate).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ idempotencyKey, performedById: 3 }) })); });
  it("replays the original record after an uncertain create response without inserting a duplicate", async () => { const cookie = signIn(UserRole.IT_STAFF, 2); mocks.ticketFindUnique.mockResolvedValue({ id: 42 }); mocks.actionFindUnique.mockResolvedValue({ ...action, idempotencyFingerprint: requestFingerprint }); const response = await request(app).post("/api/staff/tickets/42/actions").set("Cookie", cookie).set("Idempotency-Key", idempotencyKey).send({ actionDateTime: "2026-09-22T09:30:00.000Z", description: "Checked logs.", result: "Failure reproduced.", followUpRequired: false }); expect(response.status).toBe(200); expect(response.body.data.item).toMatchObject({ id: 9 }); expect(mocks.actionCreate).not.toHaveBeenCalled(); });
  it("returns the winner when concurrent retries race on the unique idempotency key", async () => { const cookie = signIn(UserRole.IT_STAFF, 2); mocks.ticketFindUnique.mockResolvedValue({ id: 42 }); mocks.actionFindUnique.mockResolvedValueOnce(null).mockResolvedValueOnce({ ...action, idempotencyFingerprint: requestFingerprint }); mocks.actionCreate.mockRejectedValue(new Prisma.PrismaClientKnownRequestError("Unique constraint failed", { code: "P2002", clientVersion: "5.22.0", meta: { target: ["idempotencyKey"] } })); const response = await request(app).post("/api/staff/tickets/42/actions").set("Cookie", cookie).set("Idempotency-Key", idempotencyKey).send({ actionDateTime: "2026-09-22T09:30:00.000Z", description: "Checked logs.", result: "Failure reproduced.", followUpRequired: false }); expect(response.status).toBe(200); expect(response.body.data.item).toMatchObject({ id: 9 }); expect(mocks.actionCreate).toHaveBeenCalledTimes(1); expect(mocks.actionFindUnique).toHaveBeenCalledTimes(2); });
  it("rejects reusing an idempotency key for a changed request instead of silently dropping edits", async () => { const cookie = signIn(UserRole.IT_STAFF, 2); mocks.ticketFindUnique.mockResolvedValue({ id: 42 }); mocks.actionFindUnique.mockResolvedValue({ ...action, idempotencyFingerprint: requestFingerprint }); const response = await request(app).post("/api/staff/tickets/42/actions").set("Cookie", cookie).set("Idempotency-Key", idempotencyKey).send({ actionDateTime: "2026-09-22T09:30:00.000Z", description: "Checked logs.", result: "Different result.", followUpRequired: false }); expect(response.status).toBe(409); expect(response.body.error.code).toBe("IDEMPOTENCY_KEY_REUSED"); expect(mocks.actionCreate).not.toHaveBeenCalled(); });
  it("requires a valid idempotency key", async () => { const cookie = signIn(UserRole.IT_STAFF, 2); const response = await request(app).post("/api/staff/tickets/42/actions").set("Cookie", cookie).send({}); expect(response.status).toBe(400); expect(response.body.error.code).toBe("VALIDATION_ERROR"); expect(mocks.ticketFindUnique).not.toHaveBeenCalled(); });
  it("requires a Follow-Up Note when follow-up is required", async () => { const cookie = signIn(UserRole.IT_STAFF); const response = await request(app).post("/api/staff/tickets/42/actions").set("Cookie", cookie).set("Idempotency-Key", idempotencyKey).send({ actionDateTime: "2026-09-22T09:30:00.000Z", description: "Checked logs.", result: "Failure reproduced.", followUpRequired: true }); expect(response.status).toBe(400); expect(response.body.error.code).toBe("VALIDATION_ERROR"); expect(mocks.actionCreate).not.toHaveBeenCalled(); });
  it("requires a valid updatedAt on every Action Taken update", async () => { const cookie = signIn(UserRole.IT_STAFF, 2); const body = { actionDateTime: "2026-09-22T09:30:00.000Z", description: "Changed.", result: "Changed.", followUpRequired: false }; const missing = await request(app).patch("/api/staff/tickets/42/actions/9").set("Cookie", cookie).send(body); const invalid = await request(app).patch("/api/staff/tickets/42/actions/9").set("Cookie", cookie).send({ ...body, updatedAt: "not-a-timestamp" }); for (const response of [missing, invalid]) { expect(response.status).toBe(400); expect(response.body.error).toMatchObject({ code: "VALIDATION_ERROR", fields: { updatedAt: expect.any(String) } }); } expect(mocks.actionUpdateMany).not.toHaveBeenCalled(); });
  it("rejects a stale Action Taken update without overwriting it", async () => { const cookie = signIn(UserRole.ADMINISTRATOR, 3); mocks.actionFindFirst.mockResolvedValue({ id: 9, updatedAt: new Date("2026-09-22T09:31:00.000Z") }); mocks.actionUpdateMany.mockResolvedValue({ count: 0 }); const response = await request(app).patch("/api/staff/tickets/42/actions/9").set("Cookie", cookie).send({ actionDateTime: "2026-09-22T09:30:00.000Z", description: "Changed.", result: "Changed.", followUpRequired: false, updatedAt: "2026-09-22T09:30:00.000Z" }); expect(response.status).toBe(409); expect(response.body.error.code).toBe("ACTION_UPDATE_CONFLICT"); expect(mocks.actionUpdateMany).toHaveBeenCalledTimes(1); });
  it("updates an Action Taken with the documented response envelope", async () => { const cookie = signIn(UserRole.IT_STAFF, 2); mocks.actionFindFirst.mockResolvedValue({ id: 9, updatedAt: new Date("2026-09-22T09:31:00.000Z") }); mocks.actionUpdateMany.mockResolvedValue({ count: 1 }); mocks.actionFindUniqueOrThrow.mockResolvedValue(action); const response = await request(app).patch("/api/staff/tickets/42/actions/9").set("Cookie", cookie).send({ actionDateTime: "2026-09-22T09:30:00.000Z", description: "Changed.", result: "Changed.", followUpRequired: false, updatedAt: "2026-09-22T09:31:00.000Z" }); expect(response.status).toBe(200); expect(response.body.data.item).toMatchObject({ id: 9 }); expect(mocks.actionUpdateMany).toHaveBeenCalledWith(expect.objectContaining({ where: expect.objectContaining({ updatedAt: new Date("2026-09-22T09:31:00.000Z") }) })); });
  it("allows Administrator to update an Action Taken with its current version", async () => { const cookie = signIn(UserRole.ADMINISTRATOR, 3); mocks.actionFindFirst.mockResolvedValue({ id: 9, updatedAt: new Date("2026-09-22T09:31:00.000Z") }); mocks.actionUpdateMany.mockResolvedValue({ count: 1 }); mocks.actionFindUniqueOrThrow.mockResolvedValue(action); const response = await request(app).patch("/api/staff/tickets/42/actions/9").set("Cookie", cookie).send({ actionDateTime: "2026-09-22T09:30:00.000Z", description: "Changed.", result: "Changed.", followUpRequired: false, updatedAt: "2026-09-22T09:31:00.000Z" }); expect(response.status).toBe(200); expect(mocks.actionUpdateMany).toHaveBeenCalledWith(expect.objectContaining({ where: { id: 9, ticketId: 42, updatedAt: new Date("2026-09-22T09:31:00.000Z") } })); });
  it("returns 404 for missing Tickets and Actions", async () => { const cookie = signIn(UserRole.ADMINISTRATOR, 3); mocks.ticketFindFirst.mockResolvedValue(null); mocks.ticketFindUnique.mockResolvedValue(null); mocks.actionFindFirst.mockResolvedValue(null); const list = await request(app).get("/api/staff/tickets/42/actions").set("Cookie", cookie); const create = await request(app).post("/api/staff/tickets/42/actions").set("Cookie", cookie).set("Idempotency-Key", idempotencyKey).send({ actionDateTime: "2026-09-22T09:30:00.000Z", description: "Checked logs.", result: "Failure reproduced.", followUpRequired: false }); const update = await request(app).patch("/api/staff/tickets/42/actions/9").set("Cookie", cookie).send({ actionDateTime: "2026-09-22T09:30:00.000Z", description: "Changed.", result: "Changed.", followUpRequired: false, updatedAt: "2026-09-22T09:31:00.000Z" }); expect(list.status).toBe(404); expect(list.body.error.code).toBe("TICKET_NOT_FOUND"); expect(create.status).toBe(404); expect(create.body.error.code).toBe("TICKET_NOT_FOUND"); expect(update.status).toBe(404); expect(update.body.error.code).toBe("ACTION_NOT_FOUND"); });
  it("rejects invalid Ticket and Action IDs", async () => { const cookie = signIn(UserRole.ADMINISTRATOR, 3); const list = await request(app).get("/api/staff/tickets/0/actions").set("Cookie", cookie); const update = await request(app).patch("/api/staff/tickets/42/actions/not-an-id").set("Cookie", cookie).send({}); expect(list.status).toBe(400); expect(list.body.error.code).toBe("INVALID_TICKET_ID"); expect(update.status).toBe(400); expect(update.body.error.code).toBe("INVALID_ACTION_ID"); expect(mocks.actionFindFirst).not.toHaveBeenCalled(); });
  it("rejects unknown performer input and overlong Action Taken text", async () => { const cookie = signIn(UserRole.IT_STAFF); const response = await request(app).post("/api/staff/tickets/42/actions").set("Cookie", cookie).set("Idempotency-Key", idempotencyKey).send({ actionDateTime: "2026-09-22T09:30:00.000Z", description: "x".repeat(5001), result: "Failure reproduced.", followUpRequired: false, performedBy: 99 }); expect(response.status).toBe(400); expect(response.body.error).toMatchObject({ code: "VALIDATION_ERROR" }); expect(mocks.actionCreate).not.toHaveBeenCalled(); });
  it("does not let a Requester create a Staff Action Taken", async () => { const cookie = signIn(UserRole.REQUESTER, 1); const response = await request(app).post("/api/staff/tickets/42/actions").set("Cookie", cookie).send({}); expect(response.status).toBe(403); expect(response.body.error.code).toBe("ROLE_FORBIDDEN"); });
});
