export type RequestedPriorityInput = "LOW" | "MEDIUM" | "HIGH";

export interface CreateTicketInput {
  submissionKey: string;
  categoryId: number;
  relatedSystemId: number;
  summary: string;
  requestedPriority: RequestedPriorityInput;
  description: string;
}

export type CreateTicketValidationResult =
  | { success: true; data: CreateTicketInput }
  | { success: false; fields: Record<string, string> };

const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const PRIORITIES = new Set<RequestedPriorityInput>(["LOW", "MEDIUM", "HIGH"]);
const SERVER_FIELDS = [
  "requesterId",
  "ticketNumber",
  "ticketDate",
  "currentStatus",
] as const;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isPositiveInteger(value: unknown): value is number {
  return Number.isSafeInteger(value) && Number(value) > 0;
}

export function validateCreateTicketInput(
  value: unknown,
): CreateTicketValidationResult {
  if (!isRecord(value)) {
    return {
      success: false,
      fields: { body: "Submit a valid Ticket request body." },
    };
  }

  const fields: Record<string, string> = {};
  const summary = typeof value.summary === "string" ? value.summary.trim() : "";
  const description =
    typeof value.description === "string" ? value.description.trim() : "";

  if (typeof value.submissionKey !== "string" || !UUID_PATTERN.test(value.submissionKey)) {
    fields.submissionKey = "Submission key must be a valid UUID.";
  }
  if (!isPositiveInteger(value.categoryId)) {
    fields.categoryId = "Select a Category.";
  }
  if (!isPositiveInteger(value.relatedSystemId)) {
    fields.relatedSystemId = "Select a Related System.";
  }
  if (summary.length < 5 || summary.length > 150) {
    fields.summary = "Summary must be between 5 and 150 characters.";
  }
  if (
    typeof value.requestedPriority !== "string" ||
    !PRIORITIES.has(value.requestedPriority as RequestedPriorityInput)
  ) {
    fields.requestedPriority = "Select Low, Medium, or High priority.";
  }
  if (description.length < 10 || description.length > 5000) {
    fields.description = "Description must be between 10 and 5000 characters.";
  }

  for (const field of SERVER_FIELDS) {
    if (Object.prototype.hasOwnProperty.call(value, field)) {
      fields[field] = "This value is generated by the server and cannot be submitted.";
    }
  }

  if (Object.keys(fields).length > 0) {
    return { success: false, fields };
  }

  return {
    success: true,
    data: {
      submissionKey: value.submissionKey as string,
      categoryId: value.categoryId as number,
      relatedSystemId: value.relatedSystemId as number,
      summary,
      requestedPriority: value.requestedPriority as RequestedPriorityInput,
      description,
    },
  };
}
